SELECT
	rec.core_table_dcid,
	rec.core_table,
	--(all other text columns)
	rec.text1,
	rec.text2,
	rec.text3,
	rec.text4,
	rec.text5,
	rec.text6,
	rec.text7,
	rec.text8,
	rec.text9,
	rec.text10,
	rec.text11,
	rec.text12,
	rec.text13,
	rec.text14,
	rec.text15,
	rec.text16,
	rec.text17,
	rec.text18,
	rec.text19,
	rec.text20,
	rec.text21,
	rec.text22,
	rec.text23,
	rec.text24,
	rec.text25,
	rec.text26,
	rec.text27,
	rec.text28,
	rec.text29,
	rec.text30,
	rec.text31,
	rec.text32,
	rec.text33,
	rec.text34,
	rec.text35,
	rec.text36,
	rec.text37,
	rec.text38,
	rec.text39,
	rec.text40,
	rec.text41,
	rec.text42,
	rec.text43,
	rec.text44,
	rec.text45,
	rec.text46,
	rec.text47,
	rec.text48,
	rec.text49,
	rec.text50,
	rec.text51,
	rec.text52,
	rec.text53,
	rec.text54,
	rec.text55,
	rec.text56,
	rec.text57,
	rec.text58,
	rec.text59,
	rec.text60,
	--(all other date columns)
	to_char(rec.date1, 'YYYY-MM-DD') AS date1,
	to_char(rec.date2, 'YYYY-MM-DD') AS date2,
	to_char(rec.date3, 'YYYY-MM-DD') AS date3,
	to_char(rec.date4, 'YYYY-MM-DD') AS date4,
	to_char(rec.date5, 'YYYY-MM-DD') AS date5,
	to_char(rec.date6, 'YYYY-MM-DD') AS date6,
	to_char(rec.date7, 'YYYY-MM-DD') AS date7,
	to_char(rec.date8, 'YYYY-MM-DD') AS date8,
	to_char(rec.date9, 'YYYY-MM-DD') AS date9,
	to_char(rec.date10, 'YYYY-MM-DD') AS date10,	
	--(all other int columns)
	rec.int1,
	rec.int2,
	rec.int3,
	rec.int4,
	rec.int5,
	rec.int6,
	rec.int7,
	rec.int8,
	rec.int9,
	rec.int10,
	--(all other double columns)
	rec.double1,
	rec.double2,
	rec.double3,
	rec.double4,
	rec.double5,
	rec.double6,
	rec.double7,
	rec.double8,
	rec.double9,
	rec.double10,
	--(all other boolean columns)
	rec.boolean1,
	rec.boolean2,
	rec.boolean3,
	rec.boolean4,
	rec.boolean5,
	rec.boolean6,
	rec.boolean7,
	rec.boolean8,
	rec.boolean9,
	rec.boolean10,
	--(all other columns)
	rec.clob,
	rec.schoolid,
	rec.yearid,
	rec.whocreated,
	to_char(rec.whencreated, 'YYYY-MM-DD HH24:MI:SS') AS whencreated,
	rec.whomodified,
	to_char(rec.whenmodified, 'YYYY-MM-DD HH24:MI:SS') AS whenmodified,
	cat.cat,
	cat.id
FROM
	u_mba_app_records rec
	JOIN u_mba_app_modules cat ON rec.u_mba_app_modulesid = cat.id
WHERE
	cat.id = 0--insert Module ID (also found from Student Module Identifier)
	AND rec.id > 0 --grabs user created records
ORDER BY
	rec.whencreated